module.exports = {
    moduleFileExtensions: ['js', 'json', 'ts'],
    rootDir: 'src',
    testRegex: '.*\\.spec\\.ts$',
    transform: {
        '^.+\\.(t|j)s$': 'ts-jest',
    },
    collectCoverageFrom: ['**/*.(t|j)s'],
    coverageDirectory: '../coverage',
    testEnvironment: 'node',
    moduleNameMapper: {
        '^src/(.*)$': '<rootDir>/$1',
    },
    roots: ['<rootDir>'],
    modulePaths: ['<rootDir>'],
    coveragePathIgnorePatterns: [
        'node_modules',
        'dist',
        'src/infrastructure/database',
        'src/domain/entities',
        'src/domain/interfaces',
        'src/shared/constants',
        'src/presentation/dto',
        'src/presentation/interceptors',
        'src/shared/configs',
        'src/shared/types',
        'src/shared/utils',
        'src/application/interfaces',
        'src/domain',
        'src/main.ts',
        'src/app.module.ts',
        'src/infrastructure/auth/decorators',
        'src/infrastructure/auth/middleware',
        'src/infrastructure/auth/strategies',
        'src/infrastructure/firestore/setup-guest-notifications.ts',
        'src/infrastructure/messaging/notification.module.spec.ts',
        'src/infrastructure/messaging/notification.module.ts',
    ],
};
