import { DeviceFingerprintingService } from './device-fingerprinting.service';

describe('DeviceFingerprintingService', () => {
    let service: DeviceFingerprintingService;
    let loggerDebugSpy: jest.SpyInstance;

    beforeEach(() => {
        service = new DeviceFingerprintingService();
        loggerDebugSpy = jest.spyOn(service['logger'], 'debug').mockImplementation(() => {});
    });

    afterEach(() => {
        jest.clearAllMocks();
    });

    describe('generateFingerprint', () => {
        it('should generate a base64 fingerprint from userAgent and clientIp', () => {
            const userAgent = 'test-agent';
            const clientIp = '1.2.3.4';
            const fingerprint = service.generateFingerprint(userAgent, clientIp);
            expect(typeof fingerprint).toBe('string');
            expect(fingerprint.length).toBe(32);
            expect(loggerDebugSpy).toHaveBeenCalledWith(
                expect.stringContaining('Generated device fingerprint: '),
            );
        });

        it('should handle missing userAgent and clientIp', () => {
            const fingerprint = service.generateFingerprint(undefined as any, undefined as any);
            expect(typeof fingerprint).toBe('string');
            expect(fingerprint.length).toBe(32);
        });
    });

    describe('getClientIp', () => {
        it('should extract x-forwarded-for from headers', () => {
            const req = {
                headers: { 'x-forwarded-for': '5.6.7.8' },
                connection: { remoteAddress: '9.9.9.9' },
            };
            expect(service.getClientIp(req)).toBe('5.6.7.8');
        });

        it('should fallback to connection.remoteAddress', () => {
            const req = { headers: {}, connection: { remoteAddress: '2.2.2.2' } };
            expect(service.getClientIp(req)).toBe('2.2.2.2');
        });

        it('should return unknown if no IP found', () => {
            const req = { headers: {}, connection: {} };
            expect(service.getClientIp(req)).toBe('unknown');
        });
    });

    describe('generateFingerprintFromRequest', () => {
        it('should generate fingerprint from request headers', () => {
            const req = {
                headers: { 'user-agent': 'ua', 'x-forwarded-for': 'ip' },
                connection: { remoteAddress: 'backup-ip' },
            };
            const fingerprint = service.generateFingerprintFromRequest(req);
            expect(typeof fingerprint).toBe('string');
            expect(fingerprint.length).toBe(28);
        });

        it('should handle missing headers gracefully', () => {
            const req = { headers: {}, connection: {} };
            const fingerprint = service.generateFingerprintFromRequest(req);
            expect(typeof fingerprint).toBe('string');
            expect(fingerprint.length).toBe(32);
        });
    });
});

describe('DeviceFingerprintingService - ensureDeviceId', () => {
    let service: DeviceFingerprintingService;
    let loggerDebugSpy: jest.SpyInstance;

    beforeEach(() => {
        service = new DeviceFingerprintingService();
        loggerDebugSpy = jest.spyOn(service['logger'], 'debug').mockImplementation(() => {});
    });

    afterEach(() => {
        jest.clearAllMocks();
    });

    it('should return the provided deviceId and isAutogenerated=false', () => {
        const result = service.ensureDeviceId('existing-device-id', {});
        expect(result.deviceId).toBe('existing-device-id');
        expect(result.isAutogenerated).toBe(false);
        expect(loggerDebugSpy).not.toHaveBeenCalled();
    });

    it('should auto-generate deviceId and set isAutogenerated=true if deviceId is missing', () => {
        const headers = {
            'user-agent': 'test-agent',
            'x-forwarded-for': '1.2.3.4',
        };
        const result = service.ensureDeviceId(undefined, headers);
        expect(typeof result.deviceId).toBe('string');
        expect(result.deviceId.length).toBe(32);
        expect(result.isAutogenerated).toBe(true);
        expect(loggerDebugSpy).toHaveBeenCalledWith(
            expect.stringContaining('Auto-generated device ID: '),
        );
    });

    it('should use UNKNOWN_AGENT and UNKNOWN_IP if headers are missing', () => {
        const result = service.ensureDeviceId(undefined, {});
        expect(typeof result.deviceId).toBe('string');
        expect(result.deviceId.length).toBe(32);
        expect(result.isAutogenerated).toBe(true);
        expect(loggerDebugSpy).toHaveBeenCalledWith(
            expect.stringContaining('Auto-generated device ID: '),
        );
    });
});
