import { Injectable, Logger } from '@nestjs/common';
import { HTTP_HEADERS } from '../constants/http-headers';

/**
 * Service for generating device fingerprints
 */
@Injectable()
export class DeviceFingerprintingService {
    private readonly logger = new Logger(DeviceFingerprintingService.name);

    /**
     * Generate a device fingerprint from user agent and IP address
     * @param userAgent The user agent string
     * @param clientIp The client IP address
     * @returns A base64 encoded device fingerprint
     */
    generateFingerprint(userAgent: string, clientIp: string): string {
        userAgent = userAgent ?? '';
        clientIp = clientIp ?? 'unknown';

        // Create a simple device fingerprint
        const sourceDeviceId = Buffer.from(`${userAgent}-${clientIp}-${Date.now()}`)
            .toString('base64')
            .substring(0, 32);

        this.logger.debug(`Generated device fingerprint: ${sourceDeviceId}`);

        return sourceDeviceId;
    }

    /**
     * Extract client IP from request
     * @param req Express request object
     * @returns The client IP address
     */
    getClientIp(req: any): string {
        return (
            req.headers[HTTP_HEADERS.X_FORWARDED_FOR] ?? req.connection.remoteAddress ?? 'unknown'
        );
    }

    /**
     * Generate device fingerprint from request object
     * @param req Express request object
     * @returns A base64 encoded device fingerprint
     */
    generateFingerprintFromRequest(req: any): string {
        const userAgent = req.headers[HTTP_HEADERS.USER_AGENT] ?? '';
        const clientIp = this.getClientIp(req);

        return this.generateFingerprint(userAgent, clientIp);
    }

    /**
     * Ensure a device ID exists, generating one if needed
     * @param deviceId Existing device ID or undefined
     * @param headers Request headers for generating a device ID if needed
     * @returns An object containing the device ID and whether it was auto-generated
     */
    ensureDeviceId(
        deviceId: string | undefined,
        headers: Record<string, any>,
    ): {
        deviceId: string;
        isAutogenerated: boolean;
    } {
        let isAutogenerated = false;

        if (!deviceId) {
            const userAgent = headers[HTTP_HEADERS.USER_AGENT] ?? HTTP_HEADERS.UNKNOWN_AGENT;
            const clientIp = headers[HTTP_HEADERS.X_FORWARDED_FOR] ?? HTTP_HEADERS.UNKNOWN_IP;

            // Generate a device ID
            deviceId = this.generateFingerprint(userAgent, clientIp);
            isAutogenerated = true;
            this.logger.debug(`Auto-generated device ID: ${deviceId}`);
        }

        return { deviceId, isAutogenerated };
    }
}
